update about choice
souffle-lang/souffle-lang.github.io pull request #58
Opened 2021-01-19 04:49 UTC by XiaowenHu96

Add documentation & example about choice-domain.

2021-01-20 07:20 UTC, azreika requested changes

2021-01-20 07:20 UTC, azreika commented on pages/docs/choice.md
> +Note here, for the sake of brevity, our syntax omit the co-domain (i.e. the right hand side of the arrow).
```suggestion
Note here, for the sake of brevity, our syntax omits the co-domain (i.e. the right hand side of the arrow). 
```

2021-01-20 07:20 UTC, azreika commented on pages/docs/choice.md
> +on `advisor` makes sure that the combination of `(stundet, year)` is unique,
```suggestion
on `advisor` makes sure that the combination of `(student, year)` is unique,
```

2021-01-20 09:49 UTC, XiaowenHu96 commented
@azreika merge it, please.

2021-01-20 09:50 UTC, azreika approved these changes

2021-01-22 06:56 UTC, b-scholz approved these changes

2021-01-22 06:56 UTC, merged